### ISSUE TITLE
click-outside does not work in Firefox

### ISSUE THREAD

**Issue by AegirLeet** [EducationLink/vue-tel-input#100]
`TypeError: n.path is undefined` at https://github.com/EducationLink/vue-tel-input/blob/086315b3cb807fa6c6a3d559819146d3fd0ab54a/src/vue-tel-input.vue#L506

This prevents the click-outside feature from working - the country list stays open.

**Comment by vesaka** [comment]
A solution of the problem can be found her:
 [https://stackoverflow.com/questions/39245488/event-path-undefined-with-firefox-and-vue-js](https://stackoverflow.com/questions/39245488/event-path-undefined-with-firefox-and-vue-js)

Had to change the build script in order to make it work.

In short, Firefox uses **event.composedPath** instead of **event.path**.

**Comment by iamstevendao** [comment]
@vesaka, @AegirLeet  Thanks for your help. the change is live on `v2.2.4`
