### ISSUE TITLE
Not working inside a Vue Web Component

### ISSUE THREAD

**Issue by benjaminroy** [EducationLink/vue-tel-input#125]
I have a Vue Web Component with a vue-tel-input field. However, the vue-tel-input field does not display correctly inside the Web Component.

See picture.

![Capture](https://user-images.githubusercontent.com/10834800/62989661-e4481d00-be16-11e9-9647-3b282a6102e9.PNG)

**Comment by iamstevendao** [comment]
@benjaminroy what version are you using?

**Comment by benjaminroy** [comment]
@iamstevendao the last one (3.1.2)

**Comment by iamstevendao** [comment]
@benjaminroy Thanks, are there any ways I can reproduce it quickly? Otherwise, I will take a look over the weekends.

**Comment by benjaminroy** [comment]
@iamstevendao https://github.com/benjaminroy/vue-web-component

By building the Vue Web Component (npm run build-wc), and then opening the demo.html in the dist folder, you can see the vue-tel-input field not rendering as supposed.

**Comment by iamstevendao** [comment]
I haven't tested yet but would it be better to include to `<script>` the cdn instead of adding the package?
https://cdn.jsdelivr.net/npm/vue-tel-input@3.1.2/dist/vue-tel-input.min.js

**Comment by benjaminroy** [comment]
@iamstevendao I can't make it work with the CDN neither, can you try on your side, maybe i'm doing something wrong?

**Comment by iamstevendao** [comment]
@benjaminroy The css was loaded in the `head` instead of the `shadow-root`.
Here might be the solution: https://stackoverflow.com/questions/53431754/styling-not-applied-to-vue-web-component-during-development/53578028#53578028

![Screen Shot 2019-08-14 at 23 16 27](https://user-images.githubusercontent.com/15044203/63024136-f47cfc80-bee9-11e9-8e14-e2f55da8d6b5.jpg)


I will close this issue as it's not an issue of `vue-tel-input`.
