### ISSUE TITLE
Input event emitting undefined

### ISSUE THREAD

**Issue by power-cut** [EducationLink/vue-tel-input#143]
the component is working correctly as per the instruction but after the update , below is what I am getting for input event, any suggestion will be great.
![image](https://user-images.githubusercontent.com/11708491/67208033-66b21600-f432-11e9-94bc-cdf47fca7110.png)

**Comment by iamstevendao** [comment]
@maverickpravin Can you reproduce it somewhere like repl.it? The demo page is using this `input` event tho.

**Comment by Daniel4Digital** [comment]
I am having the same problem.
The problem seems to exist here: https://github.com/EducationLink/vue-tel-input/blob/3407748b64129739ed38c5fee4bab25455a34129/src/components/vue-tel-input.vue#L489

If I put instead: this.$emit('input', [this.phoneText, this.phoneObject]); It works.
if I use the deprecated onInput, it works too. I've access to the phoneObject.
But using the original code, I am not able to pass the phoneObject.

In my custom-vue-tel-input component I use "<vue-tel-input v-bind="$attrs" @input="$emit('telinput', $event)"/>"

And on my app vue I am using my custom with @telinput="updatePhoneNumber"

updatePhoneNumber(phoneText, phoneObject) { this.phoneObject = phoneObject; }

If I debug that method, the phoneObject is undefined.

If I use my code all above, the $event here would receive the array instead.

Hope this info can help.

**Comment by iamstevendao** [comment]
@Daniel4Digital you need to catch the second argument too, you can do something like this:
`<vue-tel-input v-bind="$attrs" @input="emitToTelinput"/>`
`emitToTelinput(phoneText, phoneObject) { this.$emit('telinput', phoneText, phoneObject) }`

**Comment by Daniel4Digital** [comment]
That's exactly what I wanted to do, but back then it didn't worked AFAIR.
I suppose that was fixed in the meanwhile. Thanks to letting me know.
