### ISSUE TITLE
Bundle Size

### ISSUE THREAD

**Issue by ianwelerson** [EducationLink/vue-tel-input#145]
I recently upgraded from 2.5.0 to 4.0.0 and the package has significantly increased in size, showing 417kb in [bundlephobia](https://bundlephobia.com/result?p=vue-tel-input@4.0.0).

Is there any way to reduce the final size?

Here is my bundle analyzer result:

![Screen Shot 2019-10-29 at 13 46 49](https://user-images.githubusercontent.com/20309515/67789397-ab513900-fa52-11e9-90ae-b76264bfed4f.png)

**Comment by iamstevendao** [comment]
I think you are comparing the "publish size" instead of "install size". we changed the build tool to `vue-cli` from [`v3.0.0`](https://github.com/EducationLink/vue-tel-input/releases/tag/v3.0.0) and it reduced 3 times the install size of the package, from [4.8 MB(`v2.5.0`)](https://packagephobia.now.sh/result?p=vue-tel-input@2.5.0) -> [1.6 MB (`v4.0.0`)](https://packagephobia.now.sh/result?p=vue-tel-input)
