### ISSUE TITLE
Very large images are loaded upon mount

### ISSUE THREAD

**Issue by jdhartley** [EducationLink/vue-tel-input#24]
Upon mounting a `vue-tel-input` component, ALL flag images are loaded, which adds up to 4.1 MB gzipped. This is way too much, even if we lazy load the images

![image](https://user-images.githubusercontent.com/405538/42482415-2eefcf30-839c-11e8-9260-83f3cbf01707.png)

It seems that the images in `behdad/region-flags` are large files and the dimensions are way bigger than the displayed size. There's an open issue to provide alternate sizes https://github.com/behdad/region-flags/issues/12 but doesn't really seem to have much activity or push behind it.

I would propose switching to a sprite solution, maybe like [patw0929/react-intl-tel-input](https://github.com/patw0929/react-intl-tel-input)'s [sprite@2x.png](http://patw0929.github.io/react-intl-tel-input/flags@2x.png)(64.2kb) / [sprite.scss](https://github.com/patw0929/react-intl-tel-input/blob/master/src/styles/sprite.scss)

Is there any interest in an update to switch to a sprite? Any other ideas? I am interested in using this component but I cannot justify the 4.1 MB of images right now!

**Comment by iamstevendao** [comment]
@jdhartley thanks for the suggestion, we will have this in the next release very soon!

**Comment by jdhartley** [comment]
Great to hear Steven! Please let me know if I can help in any way

**Comment by jdhartley** [comment]
@iamstevendao Hey Steven! Any update on this ticket?

**Comment by iamstevendao** [comment]
@jdhartley Thanks for baring with me, [v2.0.2](https://www.npmjs.com/package/vue-tel-input) published along with this issue.

**Comment by iamstevendao** [comment]
Although it's still not the best solution, I used the same `sprite` as the react repo you commented. However, I pointed the image to the static URL link (you can find it at `src/assets/sprite.css`), which is not a good practice.
We might need to change it later, every contribution is always appreciated.

**Comment by jdhartley** [comment]
Fantastic! Thank you for this update. It has a huge impact on our app's performance.

Would love to chat through options on how we might be able to use our own CDN instead of serving off of GitHub. My fear with using that particular url is its linked to master, so if that image ever changes, people using old versions of the Sprite CSS will run into issues. It may be good to lock to a specific commit sha instead of master, or like in /dist/, add a sha to the filename.

**Comment by ajmas** [comment]
Would splitting up the flags into individual files help?

**Comment by iamstevendao** [comment]
@ajmas would you be able to give it a shot? As long as it won't increase the size of all flag images it needs to load.

**Comment by ajmas** [comment]
@iamstevendao if I have a bit of time. My next few days aren’t going to allow me to look. I encourage anyone who has a bit of time to look too. Maybe compare what other telephone widgets are doing too, even if they are angular or react based?

**Comment by blord-fullscreen** [comment]
> Would splitting up the flags into individual files help?

It would help performance if both:

- the site is only specifying a subset of the available countries (possibly true in some cases).
- the images are being requested from an HTTP/2.0 server that can multiplex lots of small files together efficiently in the response. **Note that this is currently false for content served from raw.githubusercontent.com, which does not support HTTP/2.0.**

In all other cases it will actually hurt perfomance, by ballooning the number of HTTP requests for the same content. This is why <a href="https://css-tricks.com/css-sprites/">image spriting was invented in the first place</a>.

A more flexible, possibly better solution would be a refactor allowing the developer to point to their own image resource(s), with the githubusercontent URL as a default. There could be a root path supplied as a prop, for example, and a toggle for whether the images are supplied as a sprite or as separate images.

Note that all of these refactors are breaking, which makes it all the more important to get the image URL in master to point to a specific commit SHA, as @jdhartley suggested. Otherwise updates will break things.

**Comment by ajmas** [comment]
Maybe to allow the images URL to be a configurable option would be a first step? While it doesn’t solve the issue outright, it does allow for a short term solution, for anyone not wanting to point a CDN they don’t control.
