### ISSUE TITLE
Does it really need bootstrap dependency?

### ISSUE THREAD

**Issue by raphaelarias** [EducationLink/vue-tel-input#4]

**Comment by iamstevendao** [comment]
will remove bootstrap soon

**Comment by iamstevendao** [comment]
@adrianbj it is actually in development right now, along with country search in the drop-down (#1) however it really depends on our free time so I can't promise.
Thanks for bearing with me

**Comment by adrianbj** [comment]
No problem at all - I have an imminent deadline so went for a simpler solutions for now, but may included this in v2. Thanks again!

**Comment by zeshanshani** [comment]
@iamstevendao great library. I'm also using "Bootstrap Vue" - but I'm importing its CSS file as normal CSS in HTML. So that makes it problematic for me when you are importing the whole bootstrap library in Vue component.

Also switching for now but really looking forward updated version. Great work!

**Comment by mikob** [comment]
I have removed the bootstrap dependency: https://github.com/EducationLink/vue-tel-input/pull/13

**Comment by iamstevendao** [comment]
[v2.0.0](https://www.npmjs.com/package/vue-tel-input) published along with #13 .
